# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Friends in High-Dimensional Places
tagline:          Josef Klafka's website
description:      "I'm a software engineer and researcher currently based out of Madison, Wisconsin"
url:              https://github.com/jklafka/jklafka.github.io
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Josef Klafka
  url:            https://github.com/jklafka

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/jklafka/jklafka.github.io
